version: '3.3'

services:
     
  jackett:
    container_name: jackett
    hostname: jackett
    image: linuxserver/jackett    
    ports:
     - 9117:9117
    volumes:
     - ${VOL_CONFIG}/Jackett/config:/config
     
  lidarr:
    container_name: lidarr
    hostname: lidarr
    image: linuxserver/lidarr    
    ports:
     - 8686:8686
    volumes:
     - downloaded:/data/Downloaded     
     - music:/music
     - ${VOL_CONFIG}/Lidarr/config:/config
     
  muximux:
    container_name: muximux
    hostname: muximux
    image: linuxserver/muximux
    ports:
     - 8282:80
    volumes:
     - ${VOL_CONFIG}/Muximux/config:/config
     
  ombi:
    container_name: ombi   
    expose:
     - 3579
    hostname: ombi
    image: linuxserver/ombi
    labels:
     - traefik.enable=true
     - traefik.backend=ombi     
     - traefik.frontend.rule=Host:ombi.${CF_DOMAIN}
     - traefik.port=3579
    ports:
     - 3579:3579
    volumes:
     - ${VOL_CONFIG}/Ombi/config:/config    
     
  plex:
    container_name: plex
    environment:
     - PLEX_CLAIM=${PLEX_CLAIM}
    expose:
     - 32400
    hostname: plex
    image: plexinc/pms-docker:beta    
    labels:
     - traefik.enable=true
     - traefik.backend=plex     
     - traefik.frontend.rule=Host:plex.${CF_DOMAIN}
     - traefik.port=32400
    ports:
     - 32400:32400/tcp
     - 3005:3005/tcp
     - 8324:8324/tcp
     - 32469:32469/tcp
     - 1900:1900/udp
     - 32410:32410/udp
     - 32412:32412/udp
     - 32413:32413/udp
     - 32414:32414/udp
    volumes:
     - ${PLEX_CONFIG}:/config
     - ${PLEX_TRANSCODE}:/transcode
     - media:/data
     
  plexredirect:    
    container_name: plexredirect
    hostname: plexredirect
    image: nginx
    labels:
     - traefik.enable=true
     - traefik.backend=plexredirect
     - traefik.frontend.rule=Host:${CF_DOMAIN}
     - traefik.frontend.passHostHeader=true
     - traefik.port=80    
    volumes:
     - ./plexredirect.conf:/etc/nginx/conf.d/plexredirect.conf
     - ${VOL_PLEXREDIRECT}:/usr/share/nginx/plexredirect
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/plexredirect.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
     
  radarr:
    container_name: radarr
    hostname: radarr
    image: linuxserver/radarr    
    ports:
     - 7878:7878
    volumes:
     - downloaded:/data/Downloaded     
     - media:/movies
     - ${VOL_CONFIG}/Radarr/config:/config
     
  sonarr:
    container_name: sonarr  
    hostname: sonarr
    image: linuxserver/sonarr    
    ports:
     - 8989:8989
    volumes:
     - downloaded:/data/Downloaded     
     - media:/tv
     - ${VOL_CONFIG}/Sonarr/config:/config
     
  tautulli:
    container_name: tautulli
    hostname: tautulli
    image: linuxserver/tautulli    
    ports:
     - 8181:8181    
    volumes:
     - ${PLEX_CONFIG}/Library/Application Support/Plex Media Server/Logs/:/logs:ro
     - ${VOL_CONFIG}/Tautulli/config:/config
     
  traefik:
    container_name: traefik
    hostname: traefik
    image: traefik    
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json      
      
  vpn_transmission:
    cap_add:
     - NET_ADMIN
    container_name: vpntransmission
    devices:
     - /dev/net/tun
    dns:
     - 1.1.1.1
     - 1.0.0.1
     - 209.222.18.218
     - 209.222.18.222
    environment:
     - LOCAL_NETWORK=${OVPN_LOCAL_NETWORK}
     - OPENVPN_PROVIDER=PIA 
     - OPENVPN_CONFIG=${PIA_CONFIGS} 
     - OPENVPN_USERNAME=${PIA_USERNAME} 
     - OPENVPN_PASSWORD=${PIA_PASSWORD} 
     - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
     - TRANSMISSION_ALT_SPEED_DOWN=2000 
     - TRANSMISSION_ALT_SPEED_UP=20 
     - TRANSMISSION_DOWNLOAD_DIR=${TRAN_DOWNLOAD_DIR} 
     - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
     - TRANSMISSION_IDLE_SEEDING_LIMIT=30
     - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
     - TRANSMISSION_INCOMPLETE_DIR=${TRAN_INCOMPLETE_DIR} 
     - TRANSMISSION_INCOMPLETE_DIR_ENABLED=true           
     - TRANSMISSION_RATIO_LIMIT=0
     - TRANSMISSION_RATIO_LIMIT_ENABLED=true
     - TRANSMISSION_SPEED_LIMIT_UP=100
     - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
     - TRANSMISSION_WATCH_DIR=${TRAN_WATCH_DIR}
     - TRANSMISSION_WEB_UI=combustion
     - WEBPROXY_ENABLED=true
     - WEBPROXY_PORT=8888
    hostname: vpntransmission
    image: haugene/transmission-openvpn
    logging:
      driver: json-file
      options:
        max-size: 10m    
    ports:
     - 9091:9091
     - 8888:8888
    restart: always
    volumes:
     - ${GLOB_VOL_LOCALTIME}
     - media:/data

volumes:
  media:
    external: true
  music:
    external: true
  downloaded:
    external: true
    
networks:
  media-network:
    external: true